// Secrets set via `wrangler secret put` (not in wrangler.jsonc). Merges with the
// Env interface generated by `wrangler types` in worker-configuration.d.ts.
interface Env {
  CDP_API_KEY_ID: string;
  CDP_API_KEY_SECRET: string;
  // vars from wrangler.jsonc
  X402_PAY_TO: string;
  X402_NETWORK: string;
  X402_FACILITATOR_URL: string;
  // Service binding to this same Worker (health probe / cron warmer).
  SELF: Fetcher;
  // Optional: if set, /health/dashboard requires ?token=<this>.
  DASHBOARD_TOKEN?: string;
  // Optional: enables the /playground agent test (Claude via the MCP connector).
  ANTHROPIC_API_KEY?: string;
  // Optional: private key of the agent's wallet (USDC on Base) for the paying-agent
  // test at /agent-paid. Never expose this — Worker secret only.
  PAYER_PRIVATE_KEY?: string;
  // Analytics Engine dataset (binding in wrangler.jsonc) — counts every call.
  AE?: AnalyticsEngineDataset;
  // Optional: to read the counts on /health/calls via the AE SQL API.
  CF_API_TOKEN?: string;
  CF_ACCOUNT_ID?: string;
  // Basic Auth for the back-office console (/console + private routes). If unset,
  // the console fails closed (503) — never public. Worker secrets only.
  CONSOLE_USER?: string;
  CONSOLE_PASS?: string;
  // D1 de trazas de uso (binding en wrangler.jsonc). Una fila por llamada a las
  // tools: quién (IP, wallet, país, UA), cuándo, qué y la respuesta.
  TRACES?: D1Database;
  // feedback.request_feature: token para publicar la petición como GitHub
  // Discussion (categoría "Ideas"). Classic PAT con `public_repo`, o fine-grained
  // con Discussions:read+write sobre agishub/agishub-mcp. Worker secret.
  GITHUB_TOKEN?: string;
  // Aviso por email opcional al recibir una petición (red de seguridad sobre el
  // "watch" de GitHub, que no notifica tus propias acciones). Si RESEND_API_KEY y
  // FEEDBACK_EMAIL_FROM están puestos, se envía; si no, se omite.
  RESEND_API_KEY?: string;
  FEEDBACK_EMAIL_FROM?: string; // remitente verificado en Resend, p.ej. "AgisHub <hello@agishub.com>"
  FEEDBACK_NOTIFY_EMAIL?: string; // destino del aviso; por defecto jmavid@gmail.com
}
